#!/bin/sh

# This is a generalized version of the script that I run on a crobjob to send
# me an email of my YouTube subscriptions every morning. Feel free to use and
# extend this file however you like.

name="$USER"
path="$HOME/omnavi/omnavi"
inputfile="$HOME/omnavi/example-input-file.txt"
backupfile="$HOME/backups/$(date '+%Y%m%d-%H%M%S')results.txt"
address="mail@example.com"

cat > "$backupfile" << EOF
Subject: Your YT Subscriptions for $(date '+%Y-%m-%d')
Good morning, $name,
Today is $(date '+%A, %B %d, %Y').
In the past day, your subscribed Youtube channels uploaded the following videos:

EOF

"$path" < "$inputfile" >> "$backupfile"

sendmail "$address" < "$backupfile"
